### ISSUE TITLE
GATE using more and more memory and CPU in some odd circumstances

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gateplugin-Groovy#3]
I have had this a number of times now: when running a pipeline that contains a Groovy PR, the progress bar at the bottom right of the GUI does not update properly any more (only erratically) then the GUI becomes unresponsive and does not re-paint, and eventually GATE hangs and cannot be exited even with Ctrl-C or a normal kill, needs a kill -9. 

When watching the process on jconsole, used heap memory keeps growing until all RAM is used up, GC does not do anything, CPU is getting towards 100% until the jconsole loses connection to the GATE process. 

This seems to happen when running the pipeline after re-initializing the script or scripts a number of times. If I load the pipeline and run the exact same scripts right after loading, everything works just fine. 

GATE: 8.6-SNAPSHOT build d7503bf
Groovy plugin: 8.5
Java: 1.8.0_201 Oracle
OS: Ubuntu 18.04 64b

**Comment by johann-petrak** [comment]
Steps to reproduce:
* `git clone --branch groovy-issue3 https://github.com/GateNLP/gate-lf-tutorial-textclassification1.git` 
* `cd gate-lf-tutorial-textclassification1`
* `ln -s corpora corpora-work`
* `gate.sh -tmp`
* Load application `prepared-applystats-groovy.xgapp` 
* Reinitialise the two groovy scripts a few times (I did each one three times, alternating between them)
* double click the scipts to show them in the GUI
* maybe reinitialize the scripts again 
* Run the pipeline

**Comment by greenwoodma** [comment]
I've recently had problems with the Groovy plugin using up a lot of CPU simply by trying to open the scripting PR viewer. It takes for ever for the viewer to appear while the CPU climbs and climbs, but then eventually it all returns to normal. I'm not sure if these issues are related or not, or what's causing them.

Given your's seems to be related to re-initialising the scripts that sounds like a classloader leak of some kind, although why the memory would climb as the script was being run rather than just on re-initialisation I don't know.

**Comment by johann-petrak** [comment]
I am not sure any more, when I tried to reproduce, I think opening the viewer is actually crucial. Though opening the viewer by itself does not cause the problem for me, running the pipeline afterwards makes it happen. 
Maybe you can give the steps a try and see if you can reproduce the problem on your computer or if, 
as usual, it only happens to me :)

**Comment by greenwoodma** [comment]
Yes, I can reproduce it and it is definitely related to opening the groovy script PR. It seems that something triggers a lot of updates to a Swing text pane and all the changes are stored in the undo buffer causing us to quickly run out of memory as we essentially leak millions of instances of `javax.swing.text.GapContent$UndoPosRef`.

![undo-leak](https://user-images.githubusercontent.com/3025272/52119701-d0bf2c80-2611-11e9-965a-8f3c93f38f67.png)

What I'm confused about is which pane is being updated as nothing seems to actually do any logging or anything. My guess is it's the groovy editor but I've not tracked it down yet (the heap grows so quickly I'm running out of heap space in jvisualvm to actually explore the instance data!).

I can confirm though that it doesn't happen if you don't first open the groovy script pr editor. Strangely if you load the app, open the viewer for one script, then hide the viewer, and then run the app the problem still happens which suggests that something isn't even being properly destroyed when the VR instance is closed.

I don't understand how we've not seen this before, I use the groovy PRs a lot and often have them open while running apps, which suggests it's related to the scripts themselves. The only thing I can see that differs from my stuff is that they contain before and after corpus blocks, but that would seem irrelevant.

**Comment by greenwoodma** [comment]
Having managed to capture a smaller heap dump, each of those `GapContent$UndoPosRef` instances contains an entire copy of the groovy script being displayed by the editor! I'm wondering if something odd is causing swing to redraw the pane which in turn is triggering a content change rather than a redraw and hence is being treated as an edit. If that happens on a simple redraw it would explain why the number spirals out of control so quickly. What I don't understand (yet) is why it happens in this case but not with other groovy scripts I've run.

**Comment by greenwoodma** [comment]
I hate rabbit holes!

So I now have the how, although still baffled as to why.

Essentially the groovy script PR listens to progress events and when `processFinished` is fired ensures that the editor is displaying the contents of the right script. Why it does this I have no idea, as looking at the code I can't see that it does anything other than replace the current content with the exact same thing. Now normally that shouldn't be a problem as that should only happen once processing of an entire corpus has completed. Unfortunately for some reason `processFinished` seems to be being fired repeatedly and rapidly in this specific case causing the memory leak.

What I don't know is why `processFinished` is being called. I can't see anything in the groovy scripts that would cause that to happen, but I'm not sure what's going on inside the AssignStatsPR; does it do anything that might trigger `processFinished`? Even stranger if I trigger a stack trace each time the problem occurs it seems to come from within the swing worker thread that's locking the main frame (MainFrame.java:2270):

```java.lang.RuntimeException
	at gate.groovy.gui.ScriptPREditor.setTarget(ScriptPREditor.java:156)
	at gate.groovy.gui.ScriptPREditor$3.run(ScriptPREditor.java:178)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at java.desktop/java.awt.Component.show(Component.java:1669)
	at java.desktop/java.awt.Component.setVisible(Component.java:1616)
	at java.desktop/java.awt.Window.setVisible(Window.java:1017)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
	at gate.gui.MainFrame$39.run(MainFrame.java:2270)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by ianroberts** [comment]
> Even stranger if I trigger a stack trace each time the problem occurs it seems to come from within the swing worker thread that's locking the main frame (MainFrame.java:2270):

That's a bit misleading - the `setTarget` happens in an `invokeLater` so this stack trace is just the AWT event loop, not the place that fired the `processFinished`

**Comment by greenwoodma** [comment]
ah good point, I did say it was a rabbit hole!

**Comment by greenwoodma** [comment]
Got it. So `processFinished` isn't called when the corpus finishes, but rather by the script PR itself after running the script. It calls `progressChanged(0)` when it starts then `progressChanged(100)` and `processFinished()` when the script has run. So each time a document is run through the groovy script PR it reloads the script into the editor triggering the undo handling. I'm guessing we are seeing the problem ramp up in this specific case because the processing of a single document is so fast that they come so quickly one after another.

Not sure how to fix this yet. Personally I can't see a reason why `processFinished` should reload the script so possibly removing that would fix things without breaking anything else. Having said that we should probably also look to see if we can clear out the undo data from the pane when we know we are reloading the contents from the script file.

**Comment by greenwoodma** [comment]
@johann-petrak if you upgrade to using version 8.6-SNAPSHOT of the groovy plugin then your example app now runs without any CPU or GC issues.

While I've closed the issue I'm still not sure why the editor listens to progress events and reloads the script everytime the associated PR runs. Could either you or @ianroberts have a look at the editor code around line 203 and see if you can see any reason why we do this and if it would be safe to remove? I think it should be, but while I wrote the original PR I can't remember my motivation for adding this bit of code and I want to make sure I'm not missing anything.
